### ISSUE TITLE
没有任何废话，只翻译英文的GPT

### ISSUE THREAD

**Issue by heartsblue** [YukiCoco/gpts.cat#1]
https://chat.openai.com/g/g-NbGMtRXZJ-i-will-translate-everything-to-english

I will translate everything to English
Traduciré todo al inglés! سأترجم كل شيء إلى اللغة الإنجليزية! 
我会将所有内容翻译成英文! 
全部英語に訳してみます！

**Comment by YukiCoco** [comment]
已添加您的作品，谢谢！
